tcg-salesforce/force-app/main/default/objects/Card__c/Card__c.object-meta.xml
<CustomObject>
    <label>Card</label>
    <nameField>
        <label>Card Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

tcg-salesforce/force-app/main/default/objects/Card__c/fields/Attack__c.field-meta.xml
<CustomField>
    <fullName>Attack__c</fullName>
    <inlineHelpText>Field to fill the monster attack value</inlineHelpText>
    <label>Attack</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

tcg-salesforce/force-app/main/default/objects/Card__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <inlineHelpText>Card description</inlineHelpText>
    <label>Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

tcg-salesforce/force-app/main/default/objects/Card__c/fields/EnergyCost__c.field-meta.xml
<CustomField>
    <fullName>EnergyCost__c</fullName>
    <label>Energy cost</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

tcg-salesforce/force-app/main/default/objects/Card__c/fields/Image__c.field-meta.xml
<CustomField>
    <fullName>Image__c</fullName>
    <inlineHelpText>Card image URL</inlineHelpText>
    <label>Image</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

tcg-salesforce/force-app/main/default/objects/Card__c/fields/Rarity__c.field-meta.xml
<CustomField>
    <fullName>Rarity__c</fullName>
    <label>Rarity</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Common</fullName>
            </value>
            <value>
                <fullName>Uncommon</fullName>
            </value>
            <value>
                <fullName>Rare</fullName>
            </value>
            <value>
                <fullName>Ultra Rare</fullName>
            </value>
            <value>
                <fullName>Special</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

tcg-salesforce/force-app/main/default/objects/Card__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Energy</fullName>
            </value>
            <value>
                <fullName>Monster</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

tcg-salesforce/force-app/main/default/objects/Contact/fields/LoginCode__c.field-meta.xml
<CustomField>
    <fullName>LoginCode__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Login code</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

tcg-salesforce/force-app/main/default/objects/Deck__c/Deck__c.object-meta.xml
<CustomObject>
    <label>Deck</label>
    <nameField>
        <label>Deck Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Decks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

tcg-salesforce/force-app/main/default/objects/Deck__c/fields/Player__c.field-meta.xml
<CustomField>
    <fullName>Player__c</fullName>
    <label>Player</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Decks</relationshipLabel>
    <relationshipName>Decks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

tcg-salesforce/force-app/main/default/objects/DeckCard__c/DeckCard__c.object-meta.xml
<CustomObject>
    <label>Deck Card</label>
    <nameField>
        <label>Deck Card Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deck Cards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

tcg-salesforce/force-app/main/default/objects/DeckCard__c/fields/Deck__c.field-meta.xml
<CustomField>
    <fullName>Deck__c</fullName>
    <label>Deck</label>
    <referenceTo>Deck__c</referenceTo>
    <relationshipLabel>Deck Cards</relationshipLabel>
    <relationshipName>DeckCards</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

tcg-salesforce/force-app/main/default/objects/DeckCard__c/fields/PlayerCard__c.field-meta.xml
<CustomField>
    <fullName>PlayerCard__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Player card</label>
    <referenceTo>PlayerCard__c</referenceTo>
    <relationshipLabel>Deck Cards</relationshipLabel>
    <relationshipName>DeckCards</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

tcg-salesforce/force-app/main/default/objects/PlayerCard__c/PlayerCard__c.object-meta.xml
<CustomObject>
    <label>Player Card</label>
    <nameField>
        <displayFormat>PCARD-{00000}</displayFormat>
        <label>Player Card Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Player Cards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

tcg-salesforce/force-app/main/default/objects/PlayerCard__c/fields/Card__c.field-meta.xml
<CustomField>
    <fullName>Card__c</fullName>
    <label>Card</label>
    <referenceTo>Card__c</referenceTo>
    <relationshipLabel>Player Cards</relationshipLabel>
    <relationshipName>PlayerCards</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

tcg-salesforce/force-app/main/default/objects/PlayerCard__c/fields/Player__c.field-meta.xml
<CustomField>
    <fullName>Player__c</fullName>
    <label>Player</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Player Cards</relationshipLabel>
    <relationshipName>PlayerCards</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

tcg-salesforce/force-app/main/default/game-module/deck-management/classes/DeckManagementRepository.cls
public with sharing class DeckManagementRepository {
    public List<PlayerCard__c> getPlayerCardsByPlayerLoginCode(String playerLoginCode) {
        return [
            SELECT
                Id,
                Card__c,
                Card__r.Name,
                Card__r.Attack__c,
                Card__r.Defense__c,
                Card__r.Description__c,
                Card__r.Image__c,
                Card__r.Rarity__c,
                Card__r.Type__c,
                Card__r.EnergyCost__c,
                Player__c
            FROM
                PlayerCard__c
            WHERE
                Player__r.LoginCode__c =: playerLoginCode
        ];
    }

    public List<Deck__c> getDecksByPlayerLoginCode(String playerLoginCode) {
        return [
            SELECT
                Id,
                Player__c,
                Name,
                (
                    SELECT
                        Id,
                        PlayerCard__r.Card__c,
                        PlayerCard__r.Name,
                        PlayerCard__r.Card__r.Attack__c,
                        PlayerCard__r.Card__r.Defense__c,
                        PlayerCard__r.Card__r.Description__c,
                        PlayerCard__r.Card__r.Image__c,
                        PlayerCard__r.Card__r.Rarity__c,
                        PlayerCard__r.Card__r.Type__c,
                        PlayerCard__r.Card__r.EnergyCost__c
                    FROM
                        DeckCards__r
                )
            FROM
                Deck__c
            WHERE
                Player__r.LoginCode__c =: playerLoginCode
        ];
    }

    public List<DeckCard__c> getDeckCardsByPlayerCardsIdAndDeckId(String deckId, List<String> playerCardIds) {
        return [
            SELECT
                Id
            FROM
                DeckCard__c
            WHERE
                PlayerCard__c IN: playerCardIds AND
                Deck__c =: deckId
        ];
    }
}