tcg-salesforce/force-app/main/default/objects/Card__c/Card__c.object-meta.xml
<CustomObject>
    <label>Card</label>
    <nameField>
        <label>Card Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

tcg-salesforce/force-app/main/default/objects/Card__c/fields/Attack__c.field-meta.xml
<CustomField>
    <fullName>Attack__c</fullName>
    <inlineHelpText>Field to fill the monster attack value</inlineHelpText>
    <label>Attack</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

tcg-salesforce/force-app/main/default/objects/Card__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <inlineHelpText>Card description</inlineHelpText>
    <label>Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

tcg-salesforce/force-app/main/default/objects/Card__c/fields/EnergyCost__c.field-meta.xml
<CustomField>
    <fullName>EnergyCost__c</fullName>
    <label>Energy cost</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

tcg-salesforce/force-app/main/default/objects/Card__c/fields/Image__c.field-meta.xml
<CustomField>
    <fullName>Image__c</fullName>
    <inlineHelpText>Card image URL</inlineHelpText>
    <label>Image</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

tcg-salesforce/force-app/main/default/objects/Card__c/fields/Rarity__c.field-meta.xml
<CustomField>
    <fullName>Rarity__c</fullName>
    <label>Rarity</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Common</fullName>
            </value>
            <value>
                <fullName>Uncommon</fullName>
            </value>
            <value>
                <fullName>Rare</fullName>
            </value>
            <value>
                <fullName>Ultra Rare</fullName>
            </value>
            <value>
                <fullName>Special</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

tcg-salesforce/force-app/main/default/objects/Card__c/fields/RarityColor__c.field-meta.xml
<CustomField>
    <fullName>RarityColor__c</fullName>
    <formula>IF(
    TEXT(Rarity__c) = &apos;Uncommon&apos;,
    &apos;#3801067d&apos;,
    IF(
        TEXT(Rarity__c) = &apos;Rare&apos;,
        &apos;#70267182&apos;,
        IF(
            TEXT(Rarity__c) = &apos;Ultra Rare&apos;,
            &apos;#0103387d&apos;,
            IF(
                TEXT(Rarity__c) = &apos;Special&apos;,
                &apos;#03e8ff7a&apos;,
                &apos;#26714A&apos;    
            )   
        )
    )
)</formula>
    <label>Rarity color</label>
    <type>Text</type>
</CustomField>

tcg-salesforce/force-app/main/default/objects/Card__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Energy</fullName>
            </value>
            <value>
                <fullName>Monster</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

tcg-salesforce/force-app/main/default/objects/Deck__c/Deck__c.object-meta.xml
<CustomObject>
    <label>Deck</label>
    <nameField>
        <label>Deck Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Decks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

tcg-salesforce/force-app/main/default/objects/Deck__c/fields/Player__c.field-meta.xml
<CustomField>
    <fullName>Player__c</fullName>
    <label>Player</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Decks</relationshipLabel>
    <relationshipName>Decks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

tcg-salesforce/force-app/main/default/objects/DeckCard__c/DeckCard__c.object-meta.xml
<CustomObject>
    <label>Deck Card</label>
    <nameField>
        <label>Deck Card Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deck Cards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

tcg-salesforce/force-app/main/default/objects/DeckCard__c/fields/Deck__c.field-meta.xml
<CustomField>
    <fullName>Deck__c</fullName>
    <label>Deck</label>
    <referenceTo>Deck__c</referenceTo>
    <relationshipLabel>Deck Cards</relationshipLabel>
    <relationshipName>DeckCards</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

tcg-salesforce/force-app/main/default/objects/DeckCard__c/fields/PlayerCard__c.field-meta.xml
<CustomField>
    <fullName>PlayerCard__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Player card</label>
    <referenceTo>PlayerCard__c</referenceTo>
    <relationshipLabel>Deck Cards</relationshipLabel>
    <relationshipName>DeckCards</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

tcg-salesforce/force-app/main/default/objects/Match__c/Match__c.object-meta.xml
<CustomObject>
    <label>Match</label>
    <nameField>
        <displayFormat>MATCH-{00000}</displayFormat>
        <label>Match Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Matches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

tcg-salesforce/force-app/main/default/objects/Match__c/fields/PlayerOne__c.field-meta.xml
<CustomField>
    <fullName>PlayerOne__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Player one</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Matches (Player One)</relationshipLabel>
    <relationshipName>MatchesPlayerOne</relationshipName>
    <type>Lookup</type>
</CustomField>

tcg-salesforce/force-app/main/default/objects/Match__c/fields/PlayerTwo__c.field-meta.xml
<CustomField>
    <fullName>PlayerTwo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Player two</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Matches (Player two)</relationshipLabel>
    <relationshipName>MatchesPlayerTwo</relationshipName>
    <type>Lookup</type>
</CustomField>

tcg-salesforce/force-app/main/default/objects/Match__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Waiting</fullName>
                <default>true</default>
                <label>Waiting</label>
            </value>
            <value>
                <fullName>Ongoing</fullName>
            </value>
            <value>
                <fullName>Finished</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

tcg-salesforce/force-app/main/default/objects/Match__c/fields/UpdateMatch__c.field-meta.xml
<CustomField>
    <fullName>UpdateMatch__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Update match</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

tcg-salesforce/force-app/main/default/objects/PlayerCard__c/PlayerCard__c.object-meta.xml
<CustomObject>
    <label>Player Card</label>
    <nameField>
        <displayFormat>PCARD-{00000}</displayFormat>
        <label>Player Card Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Player Cards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

tcg-salesforce/force-app/main/default/game-module/match-management/classes/MatchManagementRepository.cls
public with sharing class MatchManagementRepository {
    public Deck__c getPlayerDeck(String deckId) {
        return [
            SELECT
                Id,
                Player__c,
                Name,
                (
                    SELECT
                        Id,
                        PlayerCard__r.Card__c,
                        PlayerCard__r.Name,
                        PlayerCard__r.Card__r.Attack__c,
                        PlayerCard__r.Card__r.Defense__c,
                        PlayerCard__r.Card__r.Description__c,
                        PlayerCard__r.Card__r.Image__c,
                        PlayerCard__r.Card__r.Rarity__c,
                        PlayerCard__r.Card__r.Type__c,
                        PlayerCard__r.Card__r.EnergyCost__c,
                        PlayerCard__r.Card__r.RarityColor__c
                    FROM
                        DeckCards__r
                    ORDER BY
                        Order__c
                    ASC
                )
            FROM
                Deck__c
            WHERE
                Id =: deckId
        ];
    }

    public List<Match__c> getAnWaitingMatch() {
        return [
            SELECT
                Id,
                PlayerOne__c,
                PlayerTwo__c
            FROM
                Match__c
            WHERE
                Status__c = 'Waiting'
            ORDER BY
                CreatedDate ASC
        ];
    }

    public Match__c getMatchById(String matchId) {
        return [
            SELECT
                Id,
                UpdateMatch__c
            FROM
                Match__c
            WHERE
                Id =: matchId
        ];
    }
}