tcg-salesforce/force-app/main/default/objects/Contact/fields/LoginCode__c.field-meta.xml
<CustomField>
    <fullName>LoginCode__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Login code</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

tcg-salesforce/force-app/main/default/objects/Contact/fields/SelectedDeck__c.field-meta.xml
<CustomField>
    <fullName>SelectedDeck__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Selected Deck</label>
    <referenceTo>Deck__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

tcg-salesforce/force-app/main/default/objects/Deck__c/Deck__c.object-meta.xml
<CustomObject>
    <label>Deck</label>
    <nameField>
        <label>Deck Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Decks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

tcg-salesforce/force-app/main/default/objects/Deck__c/fields/Player__c.field-meta.xml
<CustomField>
    <fullName>Player__c</fullName>
    <label>Player</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Decks</relationshipLabel>
    <relationshipName>Decks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

tcg-salesforce/force-app/main/default/objects/DeckCard__c/DeckCard__c.object-meta.xml
<CustomObject>
    <label>Deck Card</label>
    <nameField>
        <label>Deck Card Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deck Cards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

tcg-salesforce/force-app/main/default/objects/DeckCard__c/fields/Deck__c.field-meta.xml
<CustomField>
    <fullName>Deck__c</fullName>
    <label>Deck</label>
    <referenceTo>Deck__c</referenceTo>
    <relationshipLabel>Deck Cards</relationshipLabel>
    <relationshipName>DeckCards</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

tcg-salesforce/force-app/main/default/objects/DeckCard__c/fields/PlayerCard__c.field-meta.xml
<CustomField>
    <fullName>PlayerCard__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Player card</label>
    <referenceTo>PlayerCard__c</referenceTo>
    <relationshipLabel>Deck Cards</relationshipLabel>
    <relationshipName>DeckCards</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

tcg-salesforce/force-app/main/default/objects/Match__c/Match__c.object-meta.xml
<CustomObject>
    <label>Match</label>
    <nameField>
        <displayFormat>MATCH-{00000}</displayFormat>
        <label>Match Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Matches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

tcg-salesforce/force-app/main/default/objects/Match__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Attack</fullName>
            </value>
            <value>
                <fullName>Draw card</fullName>
            </value>
            <value>
                <fullName>End turn</fullName>
            </value>
            <value>
                <fullName>Set card</fullName>
            </value>
            <value>
                <fullName>Put card on field</fullName>
            </value>
            <value>
                <fullName>Monster destroyed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

tcg-salesforce/force-app/main/default/objects/Match__c/fields/LastPlayerAction__c.field-meta.xml
<CustomField>
    <fullName>LastPlayerAction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Last player action</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Matches (Last player action)</relationshipLabel>
    <relationshipName>Matches</relationshipName>
    <type>Lookup</type>
</CustomField>

tcg-salesforce/force-app/main/default/objects/Match__c/fields/LifePointsPlayerOne__c.field-meta.xml
<CustomField>
    <fullName>LifePointsPlayerOne__c</fullName>
    <defaultValue>20</defaultValue>
    <label>Life points player one</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

tcg-salesforce/force-app/main/default/objects/Match__c/fields/LifePointsPlayerTwo__c.field-meta.xml
<CustomField>
    <fullName>LifePointsPlayerTwo__c</fullName>
    <defaultValue>20</defaultValue>
    <label>Life points player two</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

tcg-salesforce/force-app/main/default/objects/Match__c/fields/MatchEvents__c.field-meta.xml
<CustomField>
    <fullName>MatchEvents__c</fullName>
    <label>Match events</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

tcg-salesforce/force-app/main/default/objects/Match__c/fields/PlayerOne__c.field-meta.xml
<CustomField>
    <fullName>PlayerOne__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Player one</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Matches (Player One)</relationshipLabel>
    <relationshipName>MatchesPlayerOne</relationshipName>
    <type>Lookup</type>
</CustomField>

tcg-salesforce/force-app/main/default/objects/Match__c/fields/PlayerTwo__c.field-meta.xml
<CustomField>
    <fullName>PlayerTwo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Player two</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Matches (Player two)</relationshipLabel>
    <relationshipName>MatchesPlayerTwo</relationshipName>
    <type>Lookup</type>
</CustomField>

tcg-salesforce/force-app/main/default/objects/Match__c/fields/StartingMatchPlayer__c.field-meta.xml
<CustomField>
    <fullName>StartingMatchPlayer__c</fullName>
    <label>Starting match player</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Player One</fullName>
            </value>
            <value>
                <fullName>Player Two</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

tcg-salesforce/force-app/main/default/objects/Match__c/fields/Turn__c.field-meta.xml
<CustomField>
    <fullName>Turn__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Turn</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

tcg-salesforce/force-app/main/default/objects/Match__c/fields/UpdateMatch__c.field-meta.xml
<CustomField>
    <fullName>UpdateMatch__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Update match</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

tcg-salesforce/force-app/main/default/objects/MatchCemetery__c/MatchCemetery__c.object-meta.xml
<CustomObject>
    <label>Match Player Cemetery</label>
    <nameField>
        <displayFormat>MC-{00000}</displayFormat>
        <label>Match Cemetery</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Match Cemeteries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

tcg-salesforce/force-app/main/default/objects/MatchCemetery__c/fields/DeckCard__c.field-meta.xml
<CustomField>
    <fullName>DeckCard__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deck Card</label>
    <referenceTo>DeckCard__c</referenceTo>
    <relationshipLabel>Match Cemeteries</relationshipLabel>
    <relationshipName>MatchCemeteries</relationshipName>
    <type>Lookup</type>
</CustomField>

tcg-salesforce/force-app/main/default/objects/MatchCemetery__c/fields/MatchCemetery__c.field-meta.xml
<CustomField>
    <fullName>MatchCemetery__c</fullName>
    <label>Match Cemetery</label>
    <referenceTo>Match__c</referenceTo>
    <relationshipLabel>Match Cemeteries</relationshipLabel>
    <relationshipName>MatchCemeteries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

tcg-salesforce/force-app/main/default/objects/MatchCemetery__c/fields/PlayerCard__c.field-meta.xml
<CustomField>
    <fullName>PlayerCard__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Player Card</label>
    <referenceTo>PlayerCard__c</referenceTo>
    <relationshipLabel>Match Cemeteries</relationshipLabel>
    <relationshipName>MatchCemeteries</relationshipName>
    <type>Lookup</type>
</CustomField>

tcg-salesforce/force-app/main/default/objects/MatchCemetery__c/fields/PlayerCemetery__c.field-meta.xml
<CustomField>
    <fullName>PlayerCemetery__c</fullName>
    <label>PlayerCemetery</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>PlayerCemeteries</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

tcg-salesforce/force-app/main/default/objects/MatchUpdate__e/MatchUpdate__e.object-meta.xml
<CustomObject>
    <label>Match Update</label>
    <pluralLabel>Macthes Udapte</pluralLabel>
</CustomObject>

tcg-salesforce/force-app/main/default/objects/MatchUpdate__e/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

tcg-salesforce/force-app/main/default/objects/MatchUpdate__e/fields/Match__c.field-meta.xml
<CustomField>
    <fullName>Match__c</fullName>
    <label>Match</label>
    <length>130768</length>
    <type>LongTextArea</type>
</CustomField>

tcg-salesforce/force-app/main/default/objects/MatchUpdate__e/fields/MatchId__c.field-meta.xml
<CustomField>
    <fullName>MatchId__c</fullName>
    <label>MatchId</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

tcg-salesforce/force-app/main/default/objects/MatchUpdate__e/fields/PlayerLoginCode__c.field-meta.xml
<CustomField>
    <fullName>PlayerLoginCode__c</fullName>
    <label>Player Login Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

tcg-salesforce/force-app/main/default/objects/PlayerCard__c/PlayerCard__c.object-meta.xml
<CustomObject>
    <label>Player Card</label>
    <nameField>
        <displayFormat>PCARD-{00000}</displayFormat>
        <label>Player Card Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Player Cards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

tcg-salesforce/force-app/main/default/objects/PlayerCard__c/fields/Player__c.field-meta.xml
<CustomField>
    <fullName>Player__c</fullName>
    <label>Player</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Player Cards</relationshipLabel>
    <relationshipName>PlayerCards</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

tcg-salesforce/force-app/main/default/objects/PlayerHand__c/PlayerHand__c.object-meta.xml
<CustomObject>
    <label>Player Hand</label>
    <nameField>
        <displayFormat>PH-{00000}</displayFormat>
        <label>Player Hand</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Player Hands</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

tcg-salesforce/force-app/main/default/objects/PlayerHand__c/fields/ContactPlayerHand__c.field-meta.xml
<CustomField>
    <fullName>ContactPlayerHand__c</fullName>
    <label>Contact Player Hand</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Player Hands</relationshipLabel>
    <relationshipName>PlayerHands</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

tcg-salesforce/force-app/main/default/objects/PlayerHand__c/fields/DeckCard__c.field-meta.xml
<CustomField>
    <fullName>DeckCard__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deck Card</label>
    <referenceTo>DeckCard__c</referenceTo>
    <relationshipName>PlayerHands</relationshipName>
    <type>Lookup</type>
</CustomField>

tcg-salesforce/force-app/main/default/objects/PlayerHand__c/fields/MatchPlayerHand__c.field-meta.xml
<CustomField>
    <fullName>MatchPlayerHand__c</fullName>
    <label>Match</label>
    <referenceTo>Match__c</referenceTo>
    <relationshipLabel>Matche Player Hands</relationshipLabel>
    <relationshipName>PlayerHands</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

tcg-salesforce/force-app/main/default/objects/PlayerHand__c/fields/PlayerCard__c.field-meta.xml
<CustomField>
    <fullName>PlayerCard__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Player Card</label>
    <referenceTo>PlayerCard__c</referenceTo>
    <relationshipLabel>Player Hands</relationshipLabel>
    <relationshipName>PlayerHands</relationshipName>
    <type>Lookup</type>
</CustomField>

tcg-salesforce/force-app/main/default/objects/RowCard__c/RowCard__c.object-meta.xml
<CustomObject>
    <label>Match Row Card</label>
    <nameField>
        <displayFormat>RC-{00000}</displayFormat>
        <label>Row Card Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Row Cards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

tcg-salesforce/force-app/main/default/objects/RowCard__c/fields/Deckcard__c.field-meta.xml
<CustomField>
    <fullName>Deckcard__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deck card</label>
    <referenceTo>DeckCard__c</referenceTo>
    <relationshipName>RowCards</relationshipName>
    <type>Lookup</type>
</CustomField>

tcg-salesforce/force-app/main/default/game-module/match-management/classes/MatchManagement.cls
public with sharing class MatchManagement {
    MatchManagementFactory factory = new MatchManagementFactory();
    MatchManagementRepository repository = new MatchManagementRepository();
    UtilRepository utilRepository = new UtilRepository();

    public Match__c createMatch(Contact player) {
        Match__c match = this.factory.generateMatchRecord(player);
        insert match;

        return match;
    }

    public Match__c updateFoundMatch(Match__c match, Contact player) {
        match.PlayerTwo__c = player.Id;
        update match;

        return match;
    }

    public void updateMatch(Match__c match) {
        match.UpdateMatch__c += 1;
        update match;
    }

    public void updatedRowCard(RowCard__c updatedRowCard) {
        update updatedRowCard;
    }

    public void deletePlayerHandRecord(Set<Id> deckCardIds) {
        List<PlayerHand__c> playerHandsToDelete = this.repository.getPlayerHandByDeckCardIds(deckCardIds);
        delete playerHandsToDelete;
    }

    public void createMatchEvent(Contact player, String matchId, String event) {
        Match__c match = this.repository.getMatchById(matchId);
        match.LastPlayerAction__c = player.Id;
        match.Event__c = event;
        match.MatchEvents__c += event + '|';
        update match;
        //Match__c matchToUpdate = this.factory.updateMatchEvent(player, matchId, event);

        
        

        MatchUpdate__e matchUpdateEvent = new MatchUpdate__e();
        matchUpdateEvent.MatchId__c = matchId;
        matchUpdateEvent.Match__c = JSON.serialize(match);
        matchUpdateEvent.Event__c = event;
        matchUpdateEvent.PlayerLoginCode__c = player.LoginCode__c;
        EventBus.publish(matchUpdateEvent);
    }

    public void consumeEnergy(String playerLoginCode, String matchId, Decimal energyCost) {
        List<RowCard__c> rowCardsToConsume = new List<RowCard__c>();
        List<MatchCemetery__c> matchCemetery = new List<MatchCemetery__c>();

        List<RowCard__c> energyRowCards = this.repository.getCardRowsEnnergyByMatchAndPlayerLoginCode(matchId, playerLoginCode);

        Integer counter = 1;
        for(RowCard__c rowCard : energyRowCards) {
            if(counter > energyCost) { break; }
            rowCardsToConsume.add(rowCard);
            counter++;
        }

        if(!rowCardsToConsume.isEmpty()) {
            for(RowCard__c rowCard : rowCardsToConsume) {
                matchCemetery.add(new MatchCemetery__c(
                    DeckCard__c = rowCard.DeckCard__c,
                    MatchCemetery__c = matchId,
                    PlayerCemetery__c = rowCard.Deckcard__r.PlayerCard__r.Player__c
                ));
                rowCard.DeckCard__c = null;
            }
        }

        update rowCardsToConsume;
        insert matchCemetery;
    }

    public void causeDirectDamage(Integer damage, String matchId, String playerLoginCode) {
        Match__c match = this.repository.getMatchById(matchId);

        if(match.PlayerOne__r.LoginCode__c == playerLoginCode) {
            match.LifePointsPlayerTwo__c -= damage;
        }

        if(match.PlayerTwo__r.LoginCode__c == playerLoginCode) {
            match.LifePointsPlayerOne__c -= damage;
        }

        update match;
    }

    public void sendDeckCardToCemetery(String matchId, String deckCardIdToDestroy) {
        List<MatchCemetery__c> matchCemetery = new List<MatchCemetery__c>();

        List<RowCard__c> energyRowCards = this.repository.getCardRowsByDeckCardId(matchId, deckCardIdToDestroy);

        for(RowCard__c rowCard : energyRowCards) {
            matchCemetery.add(new MatchCemetery__c(
                DeckCard__c = rowCard.DeckCard__c,
                MatchCemetery__c = matchId,
                PlayerCemetery__c = rowCard.Deckcard__r.PlayerCard__r.Player__c
            ));

            rowCard.DeckCard__c = null;
        }

        update energyRowCards;
        insert matchCemetery;
    }

    public void endTurn(String matchId) {
        Match__c match = this.repository.getMatchById(matchId);
        match.Turn__c += 1;
        

        Boolean isTurnEven = (match.Turn__c - Math.floor(match.Turn__c / 2) * 2) == 0;

        DeckCard__c deckCard = null;
        if (match.StartingMatchPlayer__c == 'Player One' && isTurnEven) {
            List<DeckCard__c> deckCards = this.getPlayerAvailableDeckCards(match.PlayerOne__r.LoginCode__c, matchId);
            if(!deckCards.isEmpty()) {
                deckCard = deckCards.get(0);
            }
        } else {
            List<DeckCard__c> deckCards = this.getPlayerAvailableDeckCards(match.PlayerTwo__r.LoginCode__c, matchId);
            if(!deckCards.isEmpty()) {
                deckCard = deckCards.get(0);
            }
        }

        if(deckCard != null) {
            PlayerHand__c playerHand = new PlayerHand__c();
            playerHand.ContactPlayerHand__c = deckCard.Deck__r.Player__c;
            playerHand.DeckCard__c = deckCard.Id;
            playerHand.MatchPlayerHand__c = matchId;
            insert playerHand;
        }

        update match;
    }

    public List<DeckCard__c> getPlayerAvailableDeckCards(String playerLoginCode, String matchId) {
        Set<Id> deckCardsUsed = new Set<Id>();
        Contact player = this.utilRepository.getContactWithDecks(playerLoginCode);

        Set<Id> deckCardsOnCemetery = this.repository.getPlayerDeckCardsOnCemetery(player, matchId);
        Set<Id> deckCardsOnHand = this.repository.getPlayerDeckCardsOnHand(player, matchId);
        Set<Id> deckCardsOnField = this.repository.getPlayerDeckCardsOnField(player, matchId);

        for(Id deckCardId : deckCardsOnCemetery) {
            deckCardsUsed.add(deckCardId); 
        }

        for(Id deckCardId : deckCardsOnHand) {
            deckCardsUsed.add(deckCardId); 
        }

        for(Id deckCardId : deckCardsOnField) {
            deckCardsUsed.add(deckCardId); 
        }

        return this.repository.getPlayerAvailableDeckCards(player.SelectedDeck__c, deckCardsUsed);
    }
}