tcg-salesforce/force-app/main/default/objects/Contact/fields/LoginCode__c.field-meta.xml
<CustomField>
    <fullName>LoginCode__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Login code</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

tcg-salesforce/force-app/main/default/objects/Contact/fields/SelectedDeck__c.field-meta.xml
<CustomField>
    <fullName>SelectedDeck__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Selected Deck</label>
    <referenceTo>Deck__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

tcg-salesforce/force-app/main/default/objects/Deck__c/Deck__c.object-meta.xml
<CustomObject>
    <label>Deck</label>
    <nameField>
        <label>Deck Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Decks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

tcg-salesforce/force-app/main/default/objects/Deck__c/fields/Player__c.field-meta.xml
<CustomField>
    <fullName>Player__c</fullName>
    <label>Player</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Decks</relationshipLabel>
    <relationshipName>Decks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

tcg-salesforce/force-app/main/default/ultil-module/classes/UtilRepository.cls
public with sharing class UtilRepository {
    public Contact getContactWithDecks(String playerLoginCode) {
        List<Contact> players = [
                                SELECT
                                    Id,
                                    Name,
                                    SelectedDeck__c,
                                    LoginCode__c,
                                    (
                                        SELECT
                                            Id,
                                            Player__c
                                        FROM
                                            Decks__r
                                    )
                                FROM
                                    Contact
                                WHERE
                                    LoginCode__c =: playerLoginCode
                            ];
        if(players.isEmpty()) { return null; }

        return players.get(0);
    }
}