tcg-salesforce/force-app/main/default/objects/Match__c/Match__c.object-meta.xml
<CustomObject>
    <label>Match</label>
    <nameField>
        <displayFormat>MATCH-{00000}</displayFormat>
        <label>Match Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Matches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

tcg-salesforce/force-app/main/default/objects/Match__c/fields/PlayerOne__c.field-meta.xml
<CustomField>
    <fullName>PlayerOne__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Player one</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Matches (Player One)</relationshipLabel>
    <relationshipName>MatchesPlayerOne</relationshipName>
    <type>Lookup</type>
</CustomField>

tcg-salesforce/force-app/main/default/objects/Match__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Waiting</fullName>
                <default>true</default>
                <label>Waiting</label>
            </value>
            <value>
                <fullName>Ongoing</fullName>
            </value>
            <value>
                <fullName>Finished</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

tcg-salesforce/force-app/main/default/game-module/match-finder/classes/MatchFinderService.cls
public with sharing class MatchFinderService {
    MatchFinderRepository repository = new MatchFinderRepository();
    UtilRepository utilRepository = new UtilRepository();

    private static final MatchFinderService matchFinderServiceInstance = new MatchFinderService();
    public static MatchFinderService getInstance() {
        return matchFinderServiceInstance;
    }

    public List<Match__c> getAllWaitingMatches() {
        return this.repository.getMatchesByStatus('Waiting');
    }

    public Match__c generateMatch(String playerLoginCode) {
        Contact player = this.utilRepository.getContactWithDecks(playerLoginCode);
        
        Match__c match = new Match__c();
        match.PlayerOne__c = player.Id;
        insert match;

        return match;
    }

    public void cancelMatch(String matchId) {
        Match__c match = new Match__c();
        match.Id = matchId;
        match.Status__c = 'Cancelled';

        update match;
    }
}