tcg-salesforce/force-app/main/default/objects/BattlefieldRow__c/BattlefieldRow__c.object-meta.xml
<CustomObject>
    <label>Battlefield Row</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Battlefield Rows</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

tcg-salesforce/force-app/main/default/objects/BattlefieldRow__c/fields/Match__c.field-meta.xml
<CustomField>
    <fullName>Match__c</fullName>
    <label>Match</label>
    <referenceTo>Match__c</referenceTo>
    <relationshipLabel>Battlefield Rows</relationshipLabel>
    <relationshipName>BattlefieldRows</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

tcg-salesforce/force-app/main/default/objects/BattlefieldRow__c/fields/Player__c.field-meta.xml
<CustomField>
    <fullName>Player__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Player</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Battlefield Rows</relationshipLabel>
    <relationshipName>BattlefieldRows</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

tcg-salesforce/force-app/main/default/objects/Contact/fields/SelectedDeck__c.field-meta.xml
<CustomField>
    <fullName>SelectedDeck__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Selected Deck</label>
    <referenceTo>Deck__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

tcg-salesforce/force-app/main/default/objects/Deck__c/Deck__c.object-meta.xml
<CustomObject>
    <label>Deck</label>
    <nameField>
        <label>Deck Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Decks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

tcg-salesforce/force-app/main/default/objects/Deck__c/fields/Player__c.field-meta.xml
<CustomField>
    <fullName>Player__c</fullName>
    <label>Player</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Decks</relationshipLabel>
    <relationshipName>Decks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

tcg-salesforce/force-app/main/default/objects/DeckCard__c/DeckCard__c.object-meta.xml
<CustomObject>
    <label>Deck Card</label>
    <nameField>
        <label>Deck Card Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deck Cards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

tcg-salesforce/force-app/main/default/objects/DeckCard__c/fields/Deck__c.field-meta.xml
<CustomField>
    <fullName>Deck__c</fullName>
    <label>Deck</label>
    <referenceTo>Deck__c</referenceTo>
    <relationshipLabel>Deck Cards</relationshipLabel>
    <relationshipName>DeckCards</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

tcg-salesforce/force-app/main/default/objects/DeckCard__c/fields/PlayerCard__c.field-meta.xml
<CustomField>
    <fullName>PlayerCard__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Player card</label>
    <referenceTo>PlayerCard__c</referenceTo>
    <relationshipLabel>Deck Cards</relationshipLabel>
    <relationshipName>DeckCards</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

tcg-salesforce/force-app/main/default/objects/DeckCard__c/fields/Used__c.field-meta.xml
<CustomField>
    <fullName>Used__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Used</label>
    <type>Checkbox</type>
</CustomField>

tcg-salesforce/force-app/main/default/objects/Match__c/Match__c.object-meta.xml
<CustomObject>
    <label>Match</label>
    <nameField>
        <displayFormat>MATCH-{00000}</displayFormat>
        <label>Match Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Matches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

tcg-salesforce/force-app/main/default/objects/Match__c/fields/PlayerOne__c.field-meta.xml
<CustomField>
    <fullName>PlayerOne__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Player one</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Matches (Player One)</relationshipLabel>
    <relationshipName>MatchesPlayerOne</relationshipName>
    <type>Lookup</type>
</CustomField>

tcg-salesforce/force-app/main/default/objects/Match__c/fields/PlayerTwo__c.field-meta.xml
<CustomField>
    <fullName>PlayerTwo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Player two</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Matches (Player two)</relationshipLabel>
    <relationshipName>MatchesPlayerTwo</relationshipName>
    <type>Lookup</type>
</CustomField>

tcg-salesforce/force-app/main/default/objects/PlayerCard__c/PlayerCard__c.object-meta.xml
<CustomObject>
    <label>Player Card</label>
    <nameField>
        <displayFormat>PCARD-{00000}</displayFormat>
        <label>Player Card Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Player Cards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

tcg-salesforce/force-app/main/default/objects/PlayerCard__c/fields/Player__c.field-meta.xml
<CustomField>
    <fullName>Player__c</fullName>
    <label>Player</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Player Cards</relationshipLabel>
    <relationshipName>PlayerCards</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

tcg-salesforce/force-app/main/default/match-module/classes/MatchRepository.cls
public with sharing class MatchRepository {
    public List<Match__c> getMatches(Set<Id> matchesId) {
        return [
            SELECT
                Id,
                PlayerOne__r.SelectedDeck__c,
                PlayerTwo__r.SelectedDeck__c
            FROM
                Match__c
            WHERE
                Id In: matchesId
        ];
    }

    public Map<Id, List<DeckCard__c>> getPlayersDecks(Set<Id> playersDecksIds) {
        List<DeckCard__c> deckCards = [
                                    SELECT
                                        Id,
                                        Order__c,
                                        Deck__c,
                                        PlayerCard__r.Player__c
                                    FROM
                                        DeckCard__c
                                    WHERE
                                        Deck__c IN: playersDecksIds
        ];

        Map<Id, List<DeckCard__c>> deckCardsByPlayerId = new Map<Id, List<DeckCard__c>>();

        for(DeckCard__c deckCard : deckCards) {
            List<DeckCard__c> deckCardsFromMap = deckCardsByPlayerId.get(deckCard.PlayerCard__r.Player__c);

            if(deckCardsFromMap == null) {
                deckCardsFromMap = new List<DeckCard__c>();
            }

            deckCardsFromMap.add(deckCard);

            deckCardsByPlayerId.put(deckCard.PlayerCard__r.Player__c ,deckCardsFromMap);
        }

        return deckCardsByPlayerId;
    }

    public Map<Id, Match__c> getPlayersMatchByPlayerId(Set<Id> playerIds) {
        Map<Id, Match__c> matchesByPlayerId = new Map<Id, Match__c>();

        List<Match__c> matches = [
                                SELECT
                                    Id,
                                    PlayerOne__c,
                                    PlayerTwo__c
                                FROM
                                    Match__c
                                WHERE
                                    PlayerOne__c IN: playerIds OR
                                    PlayerTwo__c IN: playerIds
        ];

        for(Match__c match : matches) {
            matchesByPlayerId.put(match.PlayerOne__c, match);
            matchesByPlayerId.put(match.PlayerTwo__c, match);
        }

        return matchesByPlayerId;
    }

    public List<DeckCard__c> getDeckCardsByPlayerIds(Set<Id> playersIds) {
        return [
            SELECT
                Id,
                Used__c
            FROM
                DeckCard__c
            WHERE
                PlayerCard__r.Player__c IN: playersIds
            AND
                Used__c = true
        ];
    }

    public Set<String> getBattleFieldRowsPerPlayerAndMatch(Set<Id> matchesId) {
        //Map<String, List<BattlefieldRow__c>> battleFieldRowsPerPlayerAndMatch = new Map<String, List<BattlefieldRow__c>>();
        Set<String> idsPlayerAndMatch = new  Set<String>();
        
        List<BattlefieldRow__c> battlefieldRows = [
                                                    SELECT
                                                        Id,
                                                        Player__c,
                                                        Match__c
                                                    FROM
                                                        BattlefieldRow__c
                                                    WHERE
                                                        Match__c IN: matchesId
        ];

        for(BattlefieldRow__c battlefieldRow : battlefieldRows){
            idsPlayerAndMatch.add(battlefieldRow.Player__c + '' + battlefieldRow.Match__c);
        }

        return idsPlayerAndMatch;
    }
}