tcg-salesforce/force-app/main/default/objects/BattlefieldRow__c/BattlefieldRow__c.object-meta.xml
<CustomObject>
    <label>Battlefield Row</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Battlefield Rows</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

tcg-salesforce/force-app/main/default/objects/BattlefieldRow__c/fields/Match__c.field-meta.xml
<CustomField>
    <fullName>Match__c</fullName>
    <label>Match</label>
    <referenceTo>Match__c</referenceTo>
    <relationshipLabel>Battlefield Rows</relationshipLabel>
    <relationshipName>BattlefieldRows</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

tcg-salesforce/force-app/main/default/objects/Match__c/Match__c.object-meta.xml
<CustomObject>
    <label>Match</label>
    <nameField>
        <displayFormat>MATCH-{00000}</displayFormat>
        <label>Match Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Matches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

tcg-salesforce/force-app/main/default/objects/Match__c/fields/PlayerOne__c.field-meta.xml
<CustomField>
    <fullName>PlayerOne__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Player one</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Matches (Player One)</relationshipLabel>
    <relationshipName>MatchesPlayerOne</relationshipName>
    <type>Lookup</type>
</CustomField>

tcg-salesforce/force-app/main/default/objects/Match__c/fields/PlayerTwo__c.field-meta.xml
<CustomField>
    <fullName>PlayerTwo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Player two</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Matches (Player two)</relationshipLabel>
    <relationshipName>MatchesPlayerTwo</relationshipName>
    <type>Lookup</type>
</CustomField>

tcg-salesforce/force-app/main/default/objects/RowCard__c/RowCard__c.object-meta.xml
<CustomObject>
    <label>Match Row Card</label>
    <nameField>
        <displayFormat>RC-{00000}</displayFormat>
        <label>Row Card Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Row Cards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

tcg-salesforce/force-app/main/default/objects/RowCard__c/fields/BattlefieldRow__c.field-meta.xml
<CustomField>
    <fullName>BattlefieldRow__c</fullName>
    <label>Battlefield Row</label>
    <referenceTo>BattlefieldRow__c</referenceTo>
    <relationshipLabel>Row Cards</relationshipLabel>
    <relationshipName>RowCards</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

tcg-salesforce/force-app/main/default/match-module/classes/MatchService.cls
public with sharing class MatchService {
    Match match = new Match();
    Util util = new Util();

    public void generateMatchRows(List<Match__c> newMatches, Map<Id, Match__c> oldMatches) {

        List<MatchFactory.PlayerMatch> playersPerMatch = this.match.getPlayersPerMatch(newMatches, oldMatches);
        List<BattlefieldRow__c> battlefieldRows = this.match.generateBattlefieldRows(playersPerMatch);
        insert battlefieldRows;

        List<RowCard__c> rowCards = this.match.generateRowCards(battlefieldRows);
        insert rowCards;
    }

    public void blockPlayerChange(List<Match__c> newMatches, Map<Id, Match__c> oldMatches) {
        for(Match__c match : newMatches) {
            Match__c oldMatch = oldMatches.get(match.Id);

            if(this.util.isChangedToOtherValue(match, oldMatch, 'PlayerOne__c') || this.util.isChangedToOtherValue(match, oldMatch, 'PlayerTwo__c')) {
                match.addError('Player One nor Player Two can be changed on the match');
            }
        }
    }
}