tcg-salesforce/force-app/main/default/objects/BattlefieldRow__c/BattlefieldRow__c.object-meta.xml
<CustomObject>
    <label>Battlefield Row</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Battlefield Rows</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

tcg-salesforce/force-app/main/default/objects/BattlefieldRow__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Creature</fullName>
            </value>
            <value>
                <fullName>Effect</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

tcg-salesforce/force-app/main/default/objects/BattlefieldRow__c/fields/Match__c.field-meta.xml
<CustomField>
    <fullName>Match__c</fullName>
    <label>Match</label>
    <referenceTo>Match__c</referenceTo>
    <relationshipLabel>Battlefield Rows</relationshipLabel>
    <relationshipName>BattlefieldRows</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

tcg-salesforce/force-app/main/default/objects/BattlefieldRow__c/fields/Player__c.field-meta.xml
<CustomField>
    <fullName>Player__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Player</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Battlefield Rows</relationshipLabel>
    <relationshipName>BattlefieldRows</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

tcg-salesforce/force-app/main/default/objects/DeckCard__c/DeckCard__c.object-meta.xml
<CustomObject>
    <label>Deck Card</label>
    <nameField>
        <label>Deck Card Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deck Cards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

tcg-salesforce/force-app/main/default/objects/Match__c/Match__c.object-meta.xml
<CustomObject>
    <label>Match</label>
    <nameField>
        <displayFormat>MATCH-{00000}</displayFormat>
        <label>Match Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Matches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

tcg-salesforce/force-app/main/default/objects/Match__c/fields/PlayerOne__c.field-meta.xml
<CustomField>
    <fullName>PlayerOne__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Player one</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Matches (Player One)</relationshipLabel>
    <relationshipName>MatchesPlayerOne</relationshipName>
    <type>Lookup</type>
</CustomField>

tcg-salesforce/force-app/main/default/objects/Match__c/fields/PlayerTwo__c.field-meta.xml
<CustomField>
    <fullName>PlayerTwo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Player two</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Matches (Player two)</relationshipLabel>
    <relationshipName>MatchesPlayerTwo</relationshipName>
    <type>Lookup</type>
</CustomField>

tcg-salesforce/force-app/main/default/objects/PlayerHand__c/PlayerHand__c.object-meta.xml
<CustomObject>
    <label>Player Hand</label>
    <nameField>
        <displayFormat>PH-{00000}</displayFormat>
        <label>Player Hand</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Player Hands</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

tcg-salesforce/force-app/main/default/objects/PlayerHand__c/fields/ContactPlayerHand__c.field-meta.xml
<CustomField>
    <fullName>ContactPlayerHand__c</fullName>
    <label>Contact Player Hand</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Player Hands</relationshipLabel>
    <relationshipName>PlayerHands</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

tcg-salesforce/force-app/main/default/objects/PlayerHand__c/fields/DeckCard__c.field-meta.xml
<CustomField>
    <fullName>DeckCard__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deck Card</label>
    <referenceTo>DeckCard__c</referenceTo>
    <relationshipName>PlayerHands</relationshipName>
    <type>Lookup</type>
</CustomField>

tcg-salesforce/force-app/main/default/objects/PlayerHand__c/fields/MatchPlayerHand__c.field-meta.xml
<CustomField>
    <fullName>MatchPlayerHand__c</fullName>
    <label>Match</label>
    <referenceTo>Match__c</referenceTo>
    <relationshipLabel>Matche Player Hands</relationshipLabel>
    <relationshipName>PlayerHands</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

tcg-salesforce/force-app/main/default/objects/RowCard__c/RowCard__c.object-meta.xml
<CustomObject>
    <label>Match Row Card</label>
    <nameField>
        <displayFormat>RC-{00000}</displayFormat>
        <label>Row Card Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Row Cards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

tcg-salesforce/force-app/main/default/objects/RowCard__c/fields/BattlefieldRow__c.field-meta.xml
<CustomField>
    <fullName>BattlefieldRow__c</fullName>
    <label>Battlefield Row</label>
    <referenceTo>BattlefieldRow__c</referenceTo>
    <relationshipLabel>Row Cards</relationshipLabel>
    <relationshipName>RowCards</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

tcg-salesforce/force-app/main/default/objects/RowCard__c/fields/Deckcard__c.field-meta.xml
<CustomField>
    <fullName>Deckcard__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deck card</label>
    <referenceTo>DeckCard__c</referenceTo>
    <relationshipName>RowCards</relationshipName>
    <type>Lookup</type>
</CustomField>

tcg-salesforce/force-app/main/default/objects/RowConfiguration__mdt/RowConfiguration__mdt.object-meta.xml
<CustomObject>
    <label>Row Configuration</label>
    <pluralLabel>Rows Configurations</pluralLabel>
</CustomObject>

tcg-salesforce/force-app/main/default/objects/RowConfiguration__mdt/fields/NumberCards__c.field-meta.xml
<CustomField>
    <fullName>NumberCards__c</fullName>
    <label>Number of Cards</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

tcg-salesforce/force-app/main/default/objects/RowConfiguration__mdt/fields/RowCategory__c.field-meta.xml
<CustomField>
    <fullName>RowCategory__c</fullName>
    <label>Row category</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

tcg-salesforce/force-app/main/default/objects/RowConfiguration__mdt/fields/RowNumber__c.field-meta.xml
<CustomField>
    <fullName>RowNumber__c</fullName>
    <label>Row number</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

tcg-salesforce/force-app/main/default/objects/Rule__mdt/Rule__mdt.object-meta.xml
<CustomObject>
    <label>Rule</label>
    <pluralLabel>Rules</pluralLabel>
</CustomObject>

tcg-salesforce/force-app/main/default/objects/Rule__mdt/fields/NumberValue__c.field-meta.xml
<CustomField>
    <fullName>NumberValue__c</fullName>
    <label>Number value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

tcg-salesforce/force-app/main/default/match-module/classes/MatchFactory.cls
public with sharing class MatchFactory {
    Util util = new Util();

    public List<PlayerMatch> generatePlayersPerMatch(List<Match__c> matches, Map<Id, Match__c> oldMatches) {
        List<PlayerMatch> playersPerMatch = new List<PlayerMatch>();

        if(oldMatches == null) {
            return this.transformMatchesIntoPlayerMatch(matches);
        }

        for(Match__c match : matches) {
            Match__c oldMatch = oldMatches.get(match.Id);

            if(this.util.isChangedAndIsNotNull(match, oldMatch, 'PlayerOne__c')) {
                playersPerMatch.add( new PlayerMatch(match.Id, match.PlayerOne__c));
            }

            if(this.util.isChangedAndIsNotNull(match, oldMatch, 'PlayerTwo__c')) {
                playersPerMatch.add(new PlayerMatch(match.Id, match.PlayerOne__c));
            }
        }

        return playersPerMatch;
    }

    public List<PlayerMatch> transformMatchesIntoPlayerMatch(List<Match__c> matches) {
        List<PlayerMatch> playersPerMatch = new List<PlayerMatch>();

        for(Match__c match : matches) {
            if(match.PlayerOne__c != null) {
                playersPerMatch.add( new PlayerMatch(match.Id, match.PlayerOne__c));
            }

            if(match.PlayerTwo__c != null) {
                playersPerMatch.add(new PlayerMatch(match.Id, match.PlayerOne__c));
            }
        }

        return playersPerMatch;
    }

    public List<BattlefieldRow__c> generateBattlefieldRows(PlayerMatch playerPerMatch) {
        List<BattlefieldRow__c> battleFieldRowsGanerated = new List<BattlefieldRow__c>();

        Map<Decimal, RowConfiguration__mdt> rowConfigurationByRowNumber = this.generateRowConfigurationByRowNumberMap();
        Rule__mdt ruleRowsPerPlayer = Rule__mdt.getInstance('RowsPerPlayer');

        for(Integer rowCounter = 1; rowCounter <= ruleRowsPerPlayer.NumberValue__c; rowCounter++) {
            RowConfiguration__mdt rowConfiguration = rowConfigurationByRowNumber.get(rowCounter); 
            battleFieldRowsGanerated.add(new BattlefieldRow__c(
                                                            Match__c = playerPerMatch.matchId,
                                                            Player__c = playerPerMatch.playerId,
                                                            Category__c = rowConfiguration.RowCategory__c));
        }

        return battleFieldRowsGanerated;
    }

    public List<RowCard__c> generateCardRows(BattlefieldRow__c battlefieldRow) {
        List<RowCard__c> rowsCardGenerated = new List<RowCard__c>();

        Map<String, RowConfiguration__mdt> rowConfigurationByRowCategory = this.generateRowConfigurationByRowCategoryMap();
        RowConfiguration__mdt rowConfiguration = rowConfigurationByRowCategory.get(battlefieldRow.Category__c);

        for(Integer cardSlotCounter = 1; cardSlotCounter <= rowConfiguration.NumberCards__c; cardSlotCounter++) {
            rowsCardGenerated.add(new RowCard__c(
                                            BattlefieldRow__c = battlefieldRow.Id));
        }

        return rowsCardGenerated;
    }

    public Map<Decimal, RowConfiguration__mdt> generateRowConfigurationByRowNumberMap() {
        Map<Decimal, RowConfiguration__mdt> rowConfigurationByRowNumber = new Map<Decimal, RowConfiguration__mdt>();
        Map<String, RowConfiguration__mdt> rowConfigurations = RowConfiguration__mdt.getAll();

        for(RowConfiguration__mdt rowConfiguration : rowConfigurations.values()) {
            rowConfigurationByRowNumber.put(rowConfiguration.RowNumber__c, rowConfiguration);
        }

        return rowConfigurationByRowNumber;
    }

    public Map<String, RowConfiguration__mdt> generateRowConfigurationByRowCategoryMap() {
        Map<String, RowConfiguration__mdt> rowConfigurationByRowCategory = new Map<String, RowConfiguration__mdt>();
        Map<String, RowConfiguration__mdt> rowConfigurations = RowConfiguration__mdt.getAll();

        for(RowConfiguration__mdt rowConfiguration : rowConfigurations.values()) {
            rowConfigurationByRowCategory.put(rowConfiguration.RowCategory__c, rowConfiguration);
        }

        return rowConfigurationByRowCategory;
    }

    public PlayerHand__c generatePlayerhandCard(Id deckCardId, Id matchId, Id playerId) {
        PlayerHand__c playerHand = new PlayerHand__c();
        playerHand.ContactPlayerHand__c = playerId;
        playerHand.DeckCard__c = deckCardId;
        playerHand.MatchPlayerHand__c = matchId;

        return playerHand;
    }

    public class PlayerMatch {
        public PlayerMatch(Id matchId, Id playerId) {
            this.matchId = matchId;
            this.playerId = playerId;
        }

        public Id matchId { get;set; }
        public Id playerId { get;set; }
    }
}