tcg-salesforce/force-app/main/default/objects/DeckCard__c/DeckCard__c.object-meta.xml
<CustomObject>
    <label>Deck Card</label>
    <nameField>
        <label>Deck Card Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deck Cards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

tcg-salesforce/force-app/main/default/objects/Match__c/Match__c.object-meta.xml
<CustomObject>
    <label>Match</label>
    <nameField>
        <displayFormat>MATCH-{00000}</displayFormat>
        <label>Match Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Matches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

tcg-salesforce/force-app/main/default/objects/Match__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Attack</fullName>
            </value>
            <value>
                <fullName>Draw card</fullName>
            </value>
            <value>
                <fullName>End turn</fullName>
            </value>
            <value>
                <fullName>Set card</fullName>
            </value>
            <value>
                <fullName>Put card on field</fullName>
            </value>
            <value>
                <fullName>Monster destroyed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

tcg-salesforce/force-app/main/default/objects/Match__c/fields/LastPlayerAction__c.field-meta.xml
<CustomField>
    <fullName>LastPlayerAction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Last player action</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Matches (Last player action)</relationshipLabel>
    <relationshipName>Matches</relationshipName>
    <type>Lookup</type>
</CustomField>

tcg-salesforce/force-app/main/default/objects/Match__c/fields/PlayerOne__c.field-meta.xml
<CustomField>
    <fullName>PlayerOne__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Player one</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Matches (Player One)</relationshipLabel>
    <relationshipName>MatchesPlayerOne</relationshipName>
    <type>Lookup</type>
</CustomField>

tcg-salesforce/force-app/main/default/objects/MatchCemetery__c/MatchCemetery__c.object-meta.xml
<CustomObject>
    <label>Match Player Cemetery</label>
    <nameField>
        <displayFormat>MC-{00000}</displayFormat>
        <label>Match Cemetery</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Match Cemeteries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

tcg-salesforce/force-app/main/default/objects/MatchCemetery__c/fields/DeckCard__c.field-meta.xml
<CustomField>
    <fullName>DeckCard__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deck Card</label>
    <referenceTo>DeckCard__c</referenceTo>
    <relationshipLabel>Match Cemeteries</relationshipLabel>
    <relationshipName>MatchCemeteries</relationshipName>
    <type>Lookup</type>
</CustomField>

tcg-salesforce/force-app/main/default/objects/MatchCemetery__c/fields/MatchCemetery__c.field-meta.xml
<CustomField>
    <fullName>MatchCemetery__c</fullName>
    <label>Match Cemetery</label>
    <referenceTo>Match__c</referenceTo>
    <relationshipLabel>Match Cemeteries</relationshipLabel>
    <relationshipName>MatchCemeteries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

tcg-salesforce/force-app/main/default/objects/PlayerHand__c/PlayerHand__c.object-meta.xml
<CustomObject>
    <label>Player Hand</label>
    <nameField>
        <displayFormat>PH-{00000}</displayFormat>
        <label>Player Hand</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Player Hands</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

tcg-salesforce/force-app/main/default/objects/PlayerHand__c/fields/DeckCard__c.field-meta.xml
<CustomField>
    <fullName>DeckCard__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deck Card</label>
    <referenceTo>DeckCard__c</referenceTo>
    <relationshipName>PlayerHands</relationshipName>
    <type>Lookup</type>
</CustomField>

tcg-salesforce/force-app/main/default/objects/RowCard__c/RowCard__c.object-meta.xml
<CustomObject>
    <label>Match Row Card</label>
    <nameField>
        <displayFormat>RC-{00000}</displayFormat>
        <label>Row Card Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Row Cards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

tcg-salesforce/force-app/main/default/objects/RowCard__c/fields/Deckcard__c.field-meta.xml
<CustomField>
    <fullName>Deckcard__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deck card</label>
    <referenceTo>DeckCard__c</referenceTo>
    <relationshipName>RowCards</relationshipName>
    <type>Lookup</type>
</CustomField>

tcg-salesforce/force-app/main/default/game-module/match-management/classes/MatchManagementFactory.cls
public with sharing class MatchManagementFactory {
    public Match__c generateMatchRecord(Contact player) {
        Match__c match = new Match__c();
        match.PlayerOne__c = player.Id;
        
        return match;
    }

    public Match__c updateMatchEvent(Contact player, String matchId, String event) {
        return new Match__c(
            Id = matchId,
            LastPlayerAction__c = player.Id,            
            Event__c = event
        );
    }

    public class MatchData {
        @AuraEnabled
        public Contact player { get;set; }
        @AuraEnabled
        public Match__c match { get;set; }
        @AuraEnabled
        public List<DeckCard__c> deckCards { get;set; }
        @AuraEnabled
        public List<PlayerHand__c> playersHands { get;set; }
        @AuraEnabled
        public List<RowCard__c> rowCards { get;set; }
        @AuraEnabled
        public List<MatchCemetery__c> matchCemitery { get;set; }
    }
}