tcg-salesforce/force-app/main/default/objects/Deck__c/Deck__c.object-meta.xml
<CustomObject>
    <label>Deck</label>
    <nameField>
        <label>Deck Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Decks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

tcg-salesforce/force-app/main/default/objects/DeckCard__c/DeckCard__c.object-meta.xml
<CustomObject>
    <label>Deck Card</label>
    <nameField>
        <label>Deck Card Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deck Cards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

tcg-salesforce/force-app/main/default/objects/DeckCard__c/fields/Deck__c.field-meta.xml
<CustomField>
    <fullName>Deck__c</fullName>
    <label>Deck</label>
    <referenceTo>Deck__c</referenceTo>
    <relationshipLabel>Deck Cards</relationshipLabel>
    <relationshipName>DeckCards</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

tcg-salesforce/force-app/main/default/objects/DeckCard__c/fields/PlayerCard__c.field-meta.xml
<CustomField>
    <fullName>PlayerCard__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Player card</label>
    <referenceTo>PlayerCard__c</referenceTo>
    <relationshipLabel>Deck Cards</relationshipLabel>
    <relationshipName>DeckCards</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

tcg-salesforce/force-app/main/default/objects/PlayerCard__c/PlayerCard__c.object-meta.xml
<CustomObject>
    <label>Player Card</label>
    <nameField>
        <displayFormat>PCARD-{00000}</displayFormat>
        <label>Player Card Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Player Cards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

tcg-salesforce/force-app/main/default/game-module/deck-management/classes/DeckManagement.cls
public with sharing class DeckManagement {
    DeckManagementRepository repository = new DeckManagementRepository();

    public void removeCardsFromDeck(DeckManagementFactory.PlayerCardsToDeck deckCardsToRemove) {
        List<DeckCard__c> deckCards = this.repository.getDeckCardsByPlayerCardsIdAndDeckId(deckCardsToRemove.deckId, deckCardsToRemove.playerCardIds);
        Database.delete(deckCards, false);
    }

    public void addCardsToDeck(DeckManagementFactory.PlayerCardsToDeck deckCardsToAdd) {
        List<DeckCard__c> deckCards = new List<DeckCard__c>();

        for(String playerCardId : deckCardsToAdd.playerCardIds) {
            deckCards.add(new DeckCard__c(
                Deck__c = deckCardsToAdd.deckId,
                PlayerCard__c = playerCardId
            ));
        }
        Database.insert(deckCards, false);
    }
}