tcg-salesforce/force-app/main/default/objects/Deck__c/Deck__c.object-meta.xml
<CustomObject>
    <label>Deck</label>
    <nameField>
        <label>Deck Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Decks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

tcg-salesforce/force-app/main/default/objects/Deck__c/fields/Player__c.field-meta.xml
<CustomField>
    <fullName>Player__c</fullName>
    <label>Player</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Decks</relationshipLabel>
    <relationshipName>Decks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

tcg-salesforce/force-app/main/default/game-module/deck-management/classes/DeckManagementFactory.cls
public with sharing class DeckManagementFactory {
    public class PlayerCardsToDeck {
        @AuraEnabled
        public String deckId { get;set; }
        @AuraEnabled
        public List<String> playerCardIds { get;set; }
    }

    public class DeckManagementResponse {
        @AuraEnabled
        public Boolean success { get;set; }
        @AuraEnabled
        public String message { get;set; }
        @AuraEnabled
        public String recordId { get;set; }

        public DeckManagementResponse() {
            this.success = true;
            this.message = '';
            this.recordId = '';
        }
    }

    public Deck__c generateDeck(String name, Id playerId) {
        return new Deck__c(Name = name, Player__c = playerId);
    }
}